# BEGIN
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:h2:file:./test
    username: admin
    password: admin
# END
